// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package main

type FeedbackResponse struct {
	ID            string             `json:"id"`
	Feedback      []*PatientFeedback `json:"feedback"`
	ExtraFeedback *string            `json:"extraFeedback"`
}

type FeedbackResponseInput struct {
	Feedback      []*PatientFeedbackInput `json:"feedback"`
	ExtraFeedback *string                 `json:"extraFeedback"`
}

type PatientFeedback struct {
	Question string `json:"question"`
	Answer   string `json:"answer"`
}

type PatientFeedbackInput struct {
	Question string `json:"question"`
	Answer   string `json:"answer"`
}
